import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { createSnapshot } from '../src/snapshot.js';
import { validateSnapshot } from '../src/validation.js';

describe('validateSnapshot', () => {
  it('accepts snapshots generated by the current tool', async () => {
    const snapshot = await createSnapshot('fixtures/basic-repo');
    assert.equal(validateSnapshot(snapshot, 'current.json'), snapshot);
  });

  for (const [field, value, message] of [
    ['schemaVersion', 999, 'unsupported schemaVersion 999 (expected 1)'],
    ['tool', { name: 'not-repolock', version: '0.1.0' }, 'unexpected tool.name "not-repolock" (expected "repolock")'],
    ['generatedAt', 'not-a-date', 'malformed generatedAt "not-a-date" (expected an ISO 8601 timestamp)']
  ] as const) {
    it(`rejects an invalid ${field}`, async () => {
      const snapshot = await createSnapshot('fixtures/basic-repo');
      assert.throws(
        () => validateSnapshot({ ...snapshot, [field]: value }, '.tmp/invalid.json'),
        new Error(`.tmp/invalid.json: ${message}`)
      );
    });
  }
});
